import math

print(int(3 + 4) * 5)
n = int(input("Enter Value of n:"))
print(n * (n - 1) / 2)
r = int(input("Enter value of r:"))
print(4 * 3.14 * r ** 2)
a = int(input("Eter value of a:"))
b = int(input("Enter value of b:"))
print(((r * (math.cos(a) ** 2)) + (r * (math.sin(b) ** 2))) ** 0.5)
y2 = int(input("Eter value of y2:"))
y1 = int(input("Enter value of y1:"))
x2 = int(input("Eter value of x1:"))
x1 = int(input("Enter value of x2:"))
print((y2 - y1) / (x2 - x1))
